### ISSUE TITLE
"Not in a git directory" error

### ISSUE THREAD

**Issue by arthrfrts** [helaili/jekyll-action#121]
Hey, thanks for your work in this action.

Since yesterday I've been unable to deploy the latest changes in my Jekyll site. It builds everything and the job finishes without errors, but the site doesn't update.

Checking [the logs](https://github.com/arthrfrts/paomortadela/runs/5198453773?check_suite_focus=true#step:5:61), I'm seeing this:

```
Jekyll build done
Publishing to [user]/[repo] on branch gh-pages
fatal: not in a git directory
```

**Comment by helaili** [comment]
Can you give it a try with the head commit (742d0ede705b0c819d4a13d0f43d3cce07cfe832 ) of https://github.com/helaili/jekyll-action/pull/123 instead of using `2.1.0` ? If it unfortunately still fails, please run again with a repository secret `ACTIONS_STEP_DEBUG` set to `true` and point me at the logs.

**Comment by arthrfrts** [comment]
It still fails at the same error message. [Here are the debug logs[(https://github.com/arthrfrts/paomortadela/runs/5217923003?check_suite_focus=true#step:5:92).

**Comment by helaili** [comment]
`v2` tag has been moved to the latest release which includes this fix.

**Comment by arthrfrts** [comment]
Fixed, thanks!
