### ISSUE TITLE
should not only push to gh-pages but also master branch

### ISSUE THREAD

**Issue by tcitry** [helaili/jekyll-action#6]
refer to [Configuring a publishing source for GitHub Pages - Github](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages)

![image](https://user-images.githubusercontent.com/5220740/55005364-d421d380-5016-11e9-9313-6ff680bfd76d.png)

https://github.com/helaili/jekyll-action/blob/master/entrypoint.sh#L36

**Comment by helaili** [comment]
Good point @tcitry, thanks!

**Comment by helaili** [comment]
fixed by #7

**Comment by mpchadwick** [comment]
So if you have a pre-existing `.github.io` site on GitHub pages that is **not** using GitHub actions and you have been pushing to master I guess the migration path would be something like this?

- Break a new branch (e.g. "source") off of master
- Configure "source" branch under "on/push/branches" in github-pages.yml
- Push changes to "source" branch

Since the docs don't currently seem to cover this scenario just want to make sure I'm understanding.

**Comment by limjh16** [comment]
Yep, that seems correct @mpchadwick 
In any case, in a *.github.io repository, if you commit to the "master" branch, the action should throw an error so your files don't get overwritten.
